---
language: python
services: docker

env:
  global:
    - ROLE_NAME: distcc
    
# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install molecule yamllint ansible-lint docker

  # Check ansible version
  - ansible --version
  - molecule --version
  - docker --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  # Rename role to match galaxy name
  - cd ../
  - ls
  - mv ansible-role-$ROLE_NAME fgierlinger.$ROLE_NAME
  - cd fgierlinger.$ROLE_NAME

script:
  # Basic role syntax check
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
