---
# tasks file for ansible-role-distcc
#
- name: Gather OS specific variables.
  include_vars: "{{ item }}"
  with_first_found:
      - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "defaults/{{ ansible_distribution }}.yml"
      - "defaults/main.yml"

- name: install distcc
  package:
      name: '{{ package_name }}'
      state: present

- import_tasks: distcc_volunteer.yml
  when: '"volunteer" in distcc_roles'

- import_tasks: distcc_client.yml
  when: '"client" in distcc_roles'

- import_tasks: logging.yml
  when: distcc_logging|bool
