---
- name: Converge
  hosts: all
  tasks:
    - name: "Include fgierlinger.distcc"
      vars:
          distcc_roles: ['volunteer', 'client']
          distcc_volunteers:
              - addr: '127.0.0.1'
                cpus: 1
          distcc_allowed_nets: ['127.0.0.1']
      include_role: 
        name: "fgierlinger.distcc"
